version: '3'
services:
  app:
    image: ecommerce:1.0.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=dev
      - SERVER_PORT=8080
      - R2DBC_URL=r2dbc:postgresql://db:5432/ecommerce
      - R2DBC_USERNAME=postgres
      - R2DBC_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://db:5432/ecommerce
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_LOCATIONS=classpath:db/migrations
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"