spring:
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/ecommerce}
    username: ${R2DBC_USERNAME:postgres}
    password: ${R2DBC_PASSWORD:postgres}
  flyway:
    url: ${FLYWAY_URL:jdbc:postgresql://localhost:5432/ecommerce}
    user: ${FLYWAY_USER:postgres}
    password: ${FLYWAY_PASSWORD:postgres}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migrations}
server:
  port: ${SERVER_PORT:8080}